#define ACCESS_POINT_PINT 17 //SD3

#define NODEMCU_ENV 1
#define RX_PIN D6
#define TX_PIN D5
//MOTOR 
#define MOTOR_R_TURN_1_PIN D5
#define MOTOR_R_TURN_2_PIN D6
// MOTOR 2
#define MOTOR_L_TURN_1_PIN D7
#define MOTOR_L_TURN_2_PIN D8
